version: '3.2'
services:
    las:
        image: sconecuratedimages/kubernetes:las
        devices:
         - "$DEVICE"
    python:
        image: wordcount
        devices:
         - "$DEVICE"
        command: sh -c "sleep 5; SCONE_LOG=7 SCONE_LAS_ADDR=las SCONE_CAS_ADDR=$SCONE_CAS_ADDR SCONE_CONFIG_ID=$SESSION/wordcount python"  
        depends_on:
         - las
        privileged: true
